### ISSUE TITLE
Guide to forking?

### ISSUE THREAD

**Issue by josefleventon** [EBEREGIT/COVID-19-barter-trade#3]
Hi there,
I really like this project and would love to contribute to it on a fork. I seem to have noticed that there are no comments detailing the code or a guide to forking for this repository. Could you please point me in the right direction of what kind of additions this repository needs or a general guide to your requirements for forks?

Thank you,
Josef

**Comment by josefleventon** [comment]
P.S.: I have noticed, after writing this issue, that you are from Nigera; to which I understand that the COVID-19 situation in your country is very different from the one in the country where I live.

**Comment by EBEREGIT** [comment]
Hi Josef,

I really appreciate your interest in the project.

I started the project a while ago and abandoned it because I didn’t follow
certain instructions properly. I was supposed to delete the repository.

I have moved the project to
https://github.com/EBEREGIT/barter.

I will write a guide soon since you are interested in contributing.
